import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import PostDetail from "../../components/postDetail/PostDetail";
import Author from "../../components/author/Author";
import CommentForm from "../../components/commentForm/CommentForm";
import Comments from "../../components/comments/Comments";
import Categories from "../../components/categories/Categories";
import PostWidget from "../../components/postWidget/PostWidget";
import { getPostDetails, getPosts } from "../../services";
import AdjacentPosts from "../../sections/adjacentPosts/AdjacentPosts";
import Loader from "../../components/Loader";

const PostDetails = ({ post }) => {
  const router = useRouter();

  if (router.isFallback) {
    return <Loader />;
  }

  // console.log(post);

  return (
    <div className="container">
      <Head>
        <title>InfiBlogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="post-details">
        <div className="post-details-left">
          {post.map((p, i) => (
            <div key={i}>
              <PostDetail post={p} />
              <Author author={p.author} />
              <AdjacentPosts slug={p.slug} createdAt={p.createdAt} />
              <CommentForm slug={p.slug} />
              <Comments slug={p.slug} />
            </div>
          ))}
        </div>

        <div className="post-details-right">
          <Categories />
          <PostWidget />
        </div>
      </div>
    </div>
  );
};

export default PostDetails;

export async function getStaticProps({ params }) {
  const data = await getPostDetails(params.slug);

  return {
    props: {
      post: data,
    },
  };
}

export async function getStaticPaths() {
  const posts = await getPosts();

  return {
    paths: posts.map(({ node: { slug } }) => ({ params: { slug } })),
    fallback: true,
  };
}
