import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Categories from "../../components/categories/Categories";
import { getCategories, getCategoryPost } from "../../services";
import PostCard from "../../components/postCard/PostCard";
import Loader from "../../components/Loader";

const CategoryPost = ({ posts }) => {
  const router = useRouter();

  if (router.isFallback) {
    return <Loader />;
  }

  // console.log(posts);

  return (
    <div className="container">
      <Head>
        <title>InfiMovix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="home">
        <div className="home-left">
          {posts.map((post, i) => (
            <div key={i} className="home-posts">
              <PostCard post={post.node} />
            </div>
          ))}
        </div>

        <div className="home-right">
          <div>
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
};

export default CategoryPost;

export async function getStaticProps({ params }) {
  const posts = await getCategoryPost(params.slug);

  return {
    props: {
      posts,
    },
  };
}

export async function getStaticPaths() {
  const categories = await getCategories();

  return {
    paths: categories.map(({ slug }) => ({ params: { slug } })),
    fallback: true,
  };
}
