import React from "react";
import Head from "next/head";
import { getPosts } from "../../services";
import BlogPosts from "../../components/blogPosts/BlogPosts";
import PostWidget from "../../components/postWidget/PostWidget";
import Categories from "../../components/categories/Categories";

const Blogs = ({ title = "InfiBlogs | Blogs", posts }) => {
  return (
    <div className="container">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="home">
        <div className="home-left">
          {posts.map((post, i) => (
            <div key={i}>
              <BlogPosts post={post.node} />
            </div>
          ))}
        </div>

        <div className="home-right">
          <div>
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Blogs;

export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: { posts },
  };
}
